
  name: lutris
  version: 0.1
  summary: Lutris is an open source gaming platform for GNU/Linux. 
  description: |
    Lutris is an open source gaming platform for GNU/Linux. 
    It makes gaming on Linux easier by taking care of managing, installing and providing optimal settings for games.
     Lutris does not sell games, you have to provide your own copy of the games unless they are Open Source or Freeware.
     The games can be installed anywhere you want on your system, the tool does not impose anything.
     Lutris relies on various programs referenced as 'runners' to provide a vast library of games.
     These runners (with the exception of Steam and Web browsers) are provided by Lutris, you don't need to install 
     them with your package manager.
  grade: stable
  confinement: strict

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
